# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'u.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1001, 401)
        self.let_0 = QtWidgets.QLineEdit(Form)
        self.let_0.setGeometry(QtCore.QRect(30, 195, 31, 46))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.let_0.setFont(font)
        self.let_0.setText("")
        self.let_0.setReadOnly(True)
        self.let_0.setObjectName("let_0")
        self.but_0 = QtWidgets.QPushButton(Form)
        self.but_0.setGeometry(QtCore.QRect(30, 255, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.but_0.setFont(font)
        self.but_0.setObjectName("but_0")
        self.but_1 = QtWidgets.QPushButton(Form)
        self.but_1.setGeometry(QtCore.QRect(60, 255, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.but_1.setFont(font)
        self.but_1.setObjectName("but_1")
        self.let_1 = QtWidgets.QLineEdit(Form)
        self.let_1.setGeometry(QtCore.QRect(60, 195, 31, 46))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.let_1.setFont(font)
        self.let_1.setText("")
        self.let_1.setReadOnly(True)
        self.let_1.setObjectName("let_1")
        self.next = QtWidgets.QPushButton(Form)
        self.next.setGeometry(QtCore.QRect(525, 360, 93, 28))
        self.next.setObjectName("next")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(6, 379, 116, 16))
        self.label.setObjectName("label")
        self.status = QtWidgets.QLabel(Form)
        self.status.setGeometry(QtCore.QRect(130, 113, 451, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.status.setFont(font)
        self.status.setObjectName("status")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(165, 30, 372, 33))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(16)
        font.setItalic(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.let_14 = QtWidgets.QLineEdit(Form)
        self.let_14.setGeometry(QtCore.QRect(90, 195, 31, 46))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.let_14.setFont(font)
        self.let_14.setText("")
        self.let_14.setReadOnly(True)
        self.let_14.setObjectName("let_14")
        self.but_14 = QtWidgets.QPushButton(Form)
        self.but_14.setGeometry(QtCore.QRect(90, 255, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.but_14.setFont(font)
        self.but_14.setObjectName("but_14")
        self.let_15 = QtWidgets.QLineEdit(Form)
        self.let_15.setGeometry(QtCore.QRect(120, 195, 31, 46))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.let_15.setFont(font)
        self.let_15.setText("")
        self.let_15.setReadOnly(True)
        self.let_15.setObjectName("let_15")
        self.but_15 = QtWidgets.QPushButton(Form)
        self.but_15.setGeometry(QtCore.QRect(120, 255, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.but_15.setFont(font)
        self.but_15.setObjectName("but_15")
        self.let_16 = QtWidgets.QLineEdit(Form)
        self.let_16.setGeometry(QtCore.QRect(150, 195, 31, 46))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.let_16.setFont(font)
        self.let_16.setText("")
        self.let_16.setReadOnly(True)
        self.let_16.setObjectName("let_16")
        self.but_16 = QtWidgets.QPushButton(Form)
        self.but_16.setGeometry(QtCore.QRect(150, 255, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.but_16.setFont(font)
        self.but_16.setObjectName("but_16")
        self.let_17 = QtWidgets.QLineEdit(Form)
        self.let_17.setGeometry(QtCore.QRect(180, 195, 31, 46))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.let_17.setFont(font)
        self.let_17.setText("")
        self.let_17.setReadOnly(True)
        self.let_17.setObjectName("let_17")
        self.but_17 = QtWidgets.QPushButton(Form)
        self.but_17.setGeometry(QtCore.QRect(180, 255, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.but_17.setFont(font)
        self.but_17.setObjectName("but_17")
        self.let_18 = QtWidgets.QLineEdit(Form)
        self.let_18.setGeometry(QtCore.QRect(210, 195, 31, 46))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.let_18.setFont(font)
        self.let_18.setText("")
        self.let_18.setReadOnly(True)
        self.let_18.setObjectName("let_18")
        self.but_18 = QtWidgets.QPushButton(Form)
        self.but_18.setGeometry(QtCore.QRect(210, 255, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.but_18.setFont(font)
        self.but_18.setObjectName("but_18")
        self.let_19 = QtWidgets.QLineEdit(Form)
        self.let_19.setGeometry(QtCore.QRect(240, 195, 31, 46))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.let_19.setFont(font)
        self.let_19.setText("")
        self.let_19.setReadOnly(True)
        self.let_19.setObjectName("let_19")
        self.but_19 = QtWidgets.QPushButton(Form)
        self.but_19.setGeometry(QtCore.QRect(240, 255, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.but_19.setFont(font)
        self.but_19.setObjectName("but_19")
        self.let_20 = QtWidgets.QLineEdit(Form)
        self.let_20.setGeometry(QtCore.QRect(270, 195, 31, 46))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.let_20.setFont(font)
        self.let_20.setText("")
        self.let_20.setReadOnly(True)
        self.let_20.setObjectName("let_20")
        self.but_20 = QtWidgets.QPushButton(Form)
        self.but_20.setGeometry(QtCore.QRect(270, 255, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.but_20.setFont(font)
        self.but_20.setObjectName("but_20")
        self.let_21 = QtWidgets.QLineEdit(Form)
        self.let_21.setGeometry(QtCore.QRect(300, 195, 31, 46))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.let_21.setFont(font)
        self.let_21.setText("")
        self.let_21.setReadOnly(True)
        self.let_21.setObjectName("let_21")
        self.but_21 = QtWidgets.QPushButton(Form)
        self.but_21.setGeometry(QtCore.QRect(300, 255, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.but_21.setFont(font)
        self.but_21.setObjectName("but_21")
        self.let_22 = QtWidgets.QLineEdit(Form)
        self.let_22.setGeometry(QtCore.QRect(330, 195, 31, 46))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.let_22.setFont(font)
        self.let_22.setText("")
        self.let_22.setReadOnly(True)
        self.let_22.setObjectName("let_22")
        self.but_22 = QtWidgets.QPushButton(Form)
        self.but_22.setGeometry(QtCore.QRect(330, 255, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.but_22.setFont(font)
        self.but_22.setObjectName("but_22")
        self.let_23 = QtWidgets.QLineEdit(Form)
        self.let_23.setGeometry(QtCore.QRect(360, 195, 31, 46))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.let_23.setFont(font)
        self.let_23.setText("")
        self.let_23.setReadOnly(True)
        self.let_23.setObjectName("let_23")
        self.but_23 = QtWidgets.QPushButton(Form)
        self.but_23.setGeometry(QtCore.QRect(360, 255, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.but_23.setFont(font)
        self.but_23.setObjectName("but_23")
        self.let_24 = QtWidgets.QLineEdit(Form)
        self.let_24.setGeometry(QtCore.QRect(390, 195, 31, 46))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.let_24.setFont(font)
        self.let_24.setText("")
        self.let_24.setReadOnly(True)
        self.let_24.setObjectName("let_24")
        self.but_24 = QtWidgets.QPushButton(Form)
        self.but_24.setGeometry(QtCore.QRect(390, 255, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.but_24.setFont(font)
        self.but_24.setObjectName("but_24")
        self.let_25 = QtWidgets.QLineEdit(Form)
        self.let_25.setGeometry(QtCore.QRect(420, 195, 31, 46))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.let_25.setFont(font)
        self.let_25.setText("")
        self.let_25.setReadOnly(True)
        self.let_25.setObjectName("let_25")
        self.but_25 = QtWidgets.QPushButton(Form)
        self.but_25.setGeometry(QtCore.QRect(420, 255, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.but_25.setFont(font)
        self.but_25.setObjectName("but_25")
        self.left = QtWidgets.QLabel(Form)
        self.left.setGeometry(QtCore.QRect(540, 0, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.left.setFont(font)
        self.left.setObjectName("left")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(690, 0, 121, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.errors = QtWidgets.QPlainTextEdit(Form)
        self.errors.setGeometry(QtCore.QRect(705, 45, 286, 331))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.errors.setFont(font)
        self.errors.setReadOnly(True)
        self.errors.setObjectName("errors")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.but_0.setText(_translate("Form", "^"))
        self.but_1.setText(_translate("Form", "^"))
        self.next.setText(_translate("Form", "Далее>"))
        self.label.setText(_translate("Form", "(с) Лисов Кирилл"))
        self.status.setText(_translate("Form", "Нажми Далее"))
        self.label_3.setText(_translate("Form", "Тренажёр по ударениям"))
        self.but_14.setText(_translate("Form", "^"))
        self.but_15.setText(_translate("Form", "^"))
        self.but_16.setText(_translate("Form", "^"))
        self.but_17.setText(_translate("Form", "^"))
        self.but_18.setText(_translate("Form", "^"))
        self.but_19.setText(_translate("Form", "^"))
        self.but_20.setText(_translate("Form", "^"))
        self.but_21.setText(_translate("Form", "^"))
        self.but_22.setText(_translate("Form", "^"))
        self.but_23.setText(_translate("Form", "^"))
        self.but_24.setText(_translate("Form", "^"))
        self.but_25.setText(_translate("Form", "^"))
        self.left.setText(_translate("Form", "Осталось "))
        self.label_2.setText(_translate("Form", "Ошибки:"))


